### ISSUE TITLE
First message should be released automatic

### ISSUE THREAD

**Issue by soloam** [shady2k/node-red-contrib-simple-message-queue#1]
Hello, this is nice, but I think that the first message should be released automatic. I tried the code, but all messages are queued, and only released if I pass a trigger message.

**Comment by shady2k** [comment]
Not sure I understand you. Can you provide more info about what do you want? When we add a new message to the queue it always be first...

**Comment by soloam** [comment]
From what I expected, if I send 1 message and the queue is empty, that message should be immediately delivered, not expecting a trigger... if 1 message arrives and then immediately other message... the first one should be delivered and the second one should wait for the trigger,

**Comment by shady2k** [comment]
Doesn't tested, but you can solve this problem something like this:
```
				setTimeout(function() {
					if(context.queue.length == 1) {
						var m = context.queue.shift();
						node.send(m);
					}
				}, 1000);
```
Insert this timer after line 60. After first message arrived, timer will be set. If after 1 second in queue still will be only one message, it will be released.

**Comment by shady2k** [comment]
Probably answered.

**Comment by shady2k** [comment]
@soloam, added function you were requested 46376bdce161385b7102d13f33aebc4a31550244
