### ISSUE TITLE
Elements in queue are not what they are supposed to be

### ISSUE THREAD

**Issue by ebartz** [shady2k/node-red-contrib-simple-message-queue#10]
I have a function that splits up the elements of an object array. This function uses node.send to send the elements to a queue. The messages which are sent to the queue look like this:

![image](https://user-images.githubusercontent.com/6342767/64184362-a6657400-ce6b-11e9-883f-5f27a8538271.png)

But when I use the trigger to release the messages in the queue, the output is:

![image](https://user-images.githubusercontent.com/6342767/64184458-c432d900-ce6b-11e9-859d-5e1224a219ba.png)

Any idea, why this is the case?

Example flow:

`[{"id":"e198b634.7c0d48","type":"inject","z":"845afa37.42b088","name":"","topic":"","payload":"{\"Result\":[{\"name\":\"orange\",\"value\":\"2\"},{\"name\":\"purple\",\"value\":\"1\"},{\"name\":\"red\",\"value\":\"1\"},{\"name\":\"green\",\"value\":\"1\"},{\"name\":\"yellow\",\"value\":\"1\"}]}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":210,"y":660,"wires":[["a1071bb3.66afa8"]]},{"id":"a1071bb3.66afa8","type":"function","z":"845afa37.42b088","name":"split","func":"var msg2 = { 'payload': 0};\nfor (var element in msg.payload.Result){\n    if (msg.payload.Result[element].value > 0){\n      msg2.payload = msg.payload.Result[element].name + '-' + msg.payload.Result[element].value;\n      node.send(msg2);\n    }\n}","outputs":1,"noerr":0,"x":390,"y":660,"wires":[["31f3b682.52ad8a","5bd00b22.a54784"]]},{"id":"31f3b682.52ad8a","type":"simple-queue","z":"845afa37.42b088","name":"queue1","firstMessageBypass":false,"bypassInterval":"0","x":660,"y":660,"wires":[["5bd00b22.a54784"]]},{"id":"5bd00b22.a54784","type":"debug","z":"845afa37.42b088","name":"","active":true,"console":"false","complete":"true","x":850,"y":560,"wires":[]},{"id":"504154c.e9365ac","type":"inject","z":"845afa37.42b088","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":220,"y":760,"wires":[["a42da5f6.4efc38"]]},{"id":"a42da5f6.4efc38","type":"change","z":"845afa37.42b088","name":"","rules":[{"t":"set","p":"trigger","pt":"msg","to":"1","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":440,"y":760,"wires":[["31f3b682.52ad8a"]]}]`

**Comment by shady2k** [comment]
This is because you are changing the same message. Each message has the same _msgid. To remedy the situation, you need to create a new instance of the message. For example, like this:

Change you code from:
```
var msg2 = { 'payload': 0};
for (var element in msg.payload.Result){
    if (msg.payload.Result[element].value > 0){
        msg2.payload = msg.payload.Result[element].name + '-' + msg.payload.Result[element].value;
        node.send(msg2);
    }
}
```
to:
```
for (var element in msg.payload.Result){
    if (msg.payload.Result[element].value > 0){
        var msg2 = { 'payload': 0};
        msg2.payload = msg.payload.Result[element].name + '-' + msg.payload.Result[element].value;
        node.send(msg2);
    }
}
```
Now each message will have its own _msgid.
![image](https://user-images.githubusercontent.com/3366415/64191261-c0f61800-ce80-11e9-91df-9db1430bafe6.png)

**Comment by ebartz** [comment]
Yep, that seems to be my fault... Thanks for the quick response :)
