### ISSUE TITLE
With bypass first message enabled, node allows every message to bypass?

### ISSUE THREAD

**Issue by dachshund-digital** [shady2k/node-red-contrib-simple-message-queue#12]
With bypass first message enabled, node allows every message to bypass?   Node does not queue as expected.  And your example flow can[t be imported.  Node Red states "Error:  Input not a JSON array"

**Comment by shady2k** [comment]
Hello! Just checked the node and can't reproduce the problem. Also checked the example, it is imported successfully. I need more details.

**Comment by Nodi-Rubrum** [comment]
No worries... it was an artifact with how I copied the flow source that was generating the malformed json syntax, this the error.  Highlighting and scrolling to capture the text worked, double-clicking the text and letting it auto select, seemed to generate the error.  As for the by-pass, I had a loop issue in the flow.  Once I deleted the flow and recreated it, correctly, the behavior was correct.

**Comment by shady2k** [comment]
Okay, I'm glad you did it.
