### ISSUE TITLE
Testing your example flow for your node?  Having issue with the TTL feature?

### ISSUE THREAD

**Issue by dachshund-digital** [shady2k/node-red-contrib-simple-message-queue#13]
Testing your example flow for your node?  Having issue with the TTL feature?  I invoke the button that sets the TTL feature to 2000 ms.  But the message is never released from the queue, well beyond 2000 ms.  The queued message is stuck in the queue forever.  Is this a bug?  Is the example flow not working as expected?

**Comment by shady2k** [comment]
Example flow works as expected. Message with TTL property will be deleted from queue if it doesn't release in specific time. If you want to release message - pass message wwith trigger property.
