### ISSUE TITLE
Where the queue count is shown

### ISSUE THREAD

**Issue by Just-another-pleb** [shady2k/node-red-contrib-simple-message-queue#14]
Alas I have seen problems where wires going near the node obscure the number and make it difficult to see.

Would it be possible to put the number in the node?

Or make it blacker?  (Or whiter?)

I know this is a poor example but it is done to show you what I mean.

![Screenshot from 2020-12-24 21-33-42](https://user-images.githubusercontent.com/39888280/103083187-e982c200-462f-11eb-9569-7204c3a6db47.png)

Sorry.   I am not sure if the colours used are determined by the browser or not.
But wouldn't there be a way to pick a better colour than "grey"?

Thanks in advance.

**Comment by shady2k** [comment]
Sorry, but it looks like according to the documentation I cannot fix this: https://nodered.org/docs/creating-nodes/status
Try to create an issue in node-red repo: https://github.com/node-red/node-red/issues

**Comment by Just-another-pleb** [comment]
Not even the colour used?   Just `BLACK` or `WHITE` would be better contrasts than the `GREY` used now.

**Comment by shady2k** [comment]
> Not even the colour used? Just `BLACK` or `WHITE` would be better contrasts than the `GREY` used now.
Sorry, but I can't override node-red css.
