### ISSUE TITLE
Bypass interval as input

### ISSUE THREAD

**Issue by medamarko** [shady2k/node-red-contrib-simple-message-queue#15]
Hi 
Is it possible somehow dynamicaly to change bypass interval? Its ok if it can be done even only once at start.
Thanks!

**Comment by shady2k** [comment]
I'm added this ability to you. Now you can pass bypassInterval property and dynamically change bypass interval. Just download last version.
bypassInterval: Message with this property allow to dynamically change bypass interval in milliseconds from config, 0 - no bypass.
