### ISSUE TITLE
Wherews the bypass intervall?

### ISSUE THREAD

**Issue by leonardoborlot** [shady2k/node-red-contrib-simple-message-queue#16]
Hello my friend
I use your node version im some projects and did it broke some things why you modify the process. 
Could you return the bypass interval field on the node?

Thanks 

![chrome_mcmxVTBVdU](https://user-images.githubusercontent.com/20361821/106333365-42fd9280-6267-11eb-8e4c-f965bc09b4bd.png)

**Comment by leonardoborlot** [comment]
WheI send a message it don´t process the queue, just the first message...

**Comment by shady2k** [comment]
I'm not sure I understood you correctly. Last version does not modify the process. Can you explain in more detail how to reproduce the problem?

**Comment by leonardoborlot** [comment]
Hi shady. This new version havent the option to define the intervall inside os the node. Like this images. 
Maybe this is a bug...

**Comment by shady2k** [comment]
You can't see this option when trying to edit node?

**Comment by leonardoborlot** [comment]
Exactly.
When I open the node on the flow, it down't show me the options like the verios before.

**Comment by shady2k** [comment]
Ok, I understand, but I can't reproduce this. Can you delete and whern install node?

**Comment by leonardoborlot** [comment]
Lets me try and tell you again.

**Comment by leonardoborlot** [comment]
Hi man.
The problem is with the version 0.2.7.
The version 0.2.6. was working good, may you rollback?

**Comment by shady2k** [comment]
> Hi man.
> The problem is with the version 0.2.7.
> The version 0.2.6. was working good, may you rollback?

I have checked several times already on several computers and cannot reproduce the problem. Can you send screenshots?

**Comment by leonardoborlot** [comment]
Hi, sorry to be lathe man, this is "the problem", the diference by two versions. When you install from zero.
![chrome_1QW9RDfpzo](https://user-images.githubusercontent.com/20361821/118179985-60b4c900-b40c-11eb-8f84-8762e6423904.png)

**Comment by kyuumeitai** [comment]
It's strange, it happened to me too, but after uninstall and install it through the palette it works now.
If it's worth, I install a docker-compose from a git repository, on my main computer the 0.27 version works as intended. On cloning in my laptop, and without having the package installed. I installed on the palette tab, the error happens. Uninstall, and install again, and now it works as intended.

**Comment by leonardoborlot** [comment]
Hi @shady2k , you project is very good, I use it every in some projects. 
But the version 0.2.7 realy dont works good. 
Maybe you fix it on the 0.28? 
Didi you accept a little sponsor to solve it? ❤️

**Comment by shady2k** [comment]
I've made some changes on types in html file. Is it solved your problem, could you check?
