### ISSUE TITLE
when the stored messages are released is the space occupied by them in memory released too?

### ISSUE THREAD

**Issue by developer4524** [shady2k/node-red-contrib-simple-message-queue#17]
when the stored messages are released is the space occupied by them in memory released too?

**Comment by developer4524** [comment]
And in what file are they stored? what happen if the memory gets full?

**Comment by shady2k** [comment]
Hello, I do not specifically free the memory, the garbage collector (GC) of Node.js does this. Messages stored in memory, they are not written to file system. If memory gets full, probably Node.js will throw Allocation failed - JavaScript heap out of memory error.

**Comment by leonardoborlot** [comment]
Sorry to be lathe man, this is the diference of the two versions when you install from zero.

![chrome_1QW9RDfpzo](https://user-images.githubusercontent.com/20361821/118179431-a9b84d80-b40b-11eb-9750-e792f93f54da.png)

**Comment by leonardoborlot** [comment]
@shady2k , very thanks man! Did it works now!!!
