### ISSUE TITLE
Provide enable/disable input

### ISSUE THREAD

**Issue by drmibell** [shady2k/node-red-contrib-simple-message-queue#2]
Would it be possible to add a "disable" input that stops the node from queueing new messages and just passes them through until an "enable" input is received? The "disable" message would probably have to delete the queue.

See the discussion at [https://discourse.nodered.org/t/gate-node-using-blockly/2830/17](url) for the reasons behind this suggestion.

**Comment by shady2k** [comment]
Add bypass property in 5c7d53aa64b1b0af2fd16ae4a86b931183f11a4b
