### ISSUE TITLE
let first massage pass throug without the trigger. 

### ISSUE THREAD

**Issue by echtelerp** [shady2k/node-red-contrib-simple-message-queue#3]
Hi shady2k, 

first: very good work. This node might solve my problem :-)
now to my issue. 
Assuming, that I want to use the queue to only send a packet via UDP when I have rescieved the answer to the previous request. 

scematic process: 
build first UDP Packet -> send to "hardware" via UDP OUT node ->"hardware" builds the answer -> sends the answer back to the UDP in Node -> trigger to send the next packet, 

my problem now is, the first sending of the initial packet, to trigger the process, as well as when the process has finished, to restart it again. 

I need to prevent: sending a UDP packet before I have rescived an answer. 

Flow: 
[{"id":"226db837.f68348","type":"simple-queue","z":"8d110f9b.a77ac","name":"UDP Handler Queue","x":300,"y":320,"wires":[["3020a241.46667e","93697a6c.7c14b8"]]},{"id":"3020a241.46667e","type":"udp out","z":"8d110f9b.a77ac","name":"UDP Output node","addr":"","iface":"","port":"","ipv":"udp4","outport":"2000","base64":false,"multicast":"false","x":530,"y":320,"wires":[]},{"id":"1c77621f.41d91e","type":"udp in","z":"8d110f9b.a77ac","name":"UDP Input node","iface":"","port":"2000","ipv":"udp4","multicast":"false","group":"","datatype":"buffer","x":720,"y":320,"wires":[["fd1c5007.6d4a1","41dc46c4.f49368"]]},{"id":"41dc46c4.f49368","type":"change","z":"8d110f9b.a77ac","name":"Release next massage in queue","rules":[{"t":"set","p":"trigger","pt":"msg","to":"1","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":570,"y":200,"wires":[["226db837.f68348","70b1a31e.8f580c"]]},{"id":"70b1a31e.8f580c","type":"debug","z":"8d110f9b.a77ac","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":810,"y":200,"wires":[]},{"id":"70b46782.73f918","type":"inject","z":"8d110f9b.a77ac","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":360,"y":140,"wires":[["41dc46c4.f49368"]]},{"id":"fd1c5007.6d4a1","type":"debug","z":"8d110f9b.a77ac","name":"incoming massages Debug","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":920,"y":420,"wires":[]},{"id":"547e2072.a4952","type":"debug","z":"8d110f9b.a77ac","name":"Outgoing massages Debug","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":320,"y":420,"wires":[]},{"id":"93697a6c.7c14b8","type":"debug","z":"8d110f9b.a77ac","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":480,"y":520,"wires":[]},{"id":"fef7b888.8a69c8","type":"inject","z":"8d110f9b.a77ac","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":100,"y":320,"wires":[["226db837.f68348","547e2072.a4952"]]}]

**Comment by shady2k** [comment]
@echtelerp, check 46376bdce161385b7102d13f33aebc4a31550244

**Comment by echtelerp** [comment]
Hi Shady2k, 
sorry for the delay. 
I tested the node, and jep man, nice Work! :-) 
Love it. it works the way as expected :-)

**Comment by shady2k** [comment]
Perfect, thanks for feedback.
