### ISSUE TITLE
trigger=true not moving to next item in the queue

### ISSUE THREAD

**Issue by githubbuh** [shady2k/node-red-contrib-simple-message-queue#7]
simple-queue v0.2.2

Here is a sample sequence to illustrate that a trigger = true message is not releasing the next item in the queue.

**Before i forget, Thank You for the queueCount enhancement!!!!!**

I have rolled back to version 0.2.1, and trigger=true is working as designed.

[
    {
        "id": "10cdd636.bf60f2",
        "type": "function",
        "z": "8e729ba9.64339",
        "name": "group_str_parse",
        "func": "var array = [];\nvar seqStr;\nvar cntStr;\nvar lastStr;\nvar runMode;\nvar runEvent;\n\n\nfor (var i=0; i<msg.payload.group.length;i++) {\n// add 1 to i to fix off-by-one so that the first\n// is 1\n    seqStr = i + 1;\n    cntStr = msg.payload.group.length;\n    lastStr = \"false\";\n    runMode = msg.run_mode;\n    runEvent = msg.run_event;\n\n    if ((msg.payload.group.length - i) == 1)\n    {\n        lastStr = \"true\";\n    }\n    \n    msg.payload.group[i].seq = seqStr;\n    msg.payload.group[i].cnt = cntStr;\n    msg.payload.group[i].last = lastStr;\n    msg.payload.group[i].run_event = runEvent;\n    \n    if (runMode == \"batch\")\n    {\n        msg.payload.group[i].run_mode = runMode;\n    }\n    else if (runMode == \"calendar\")\n    {\n        msg.payload.group[i].run_mode = runMode;\n    }\n    \n    array.push({payload: msg.payload.group[i]});\n}\n\nreturn [array];",
        "outputs": 1,
        "noerr": 0,
        "x": 785,
        "y": 440,
        "wires": [
            [
                "bffe3c19.05eca"
            ]
        ]
    },
    {
        "id": "aef9c512.2f577",
        "type": "debug",
        "z": "8e729ba9.64339",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "x": 1052.3931884765625,
        "y": 383.8213653564453,
        "wires": []
    },
    {
        "id": "bffe3c19.05eca",
        "type": "simple-queue",
        "z": "8e729ba9.64339",
        "name": "irrigation_queue",
        "firstMessageBypass": false,
        "bypassInterval": "0",
        "x": 1036.9407958984375,
        "y": 572.8689575195312,
        "wires": [
            [
                "d51fec69.4ff1b",
                "65655784.e0c5c8"
            ]
        ]
    },
    {
        "id": "865c84e8.d62208",
        "type": "change",
        "z": "8e729ba9.64339",
        "name": "queue_move_to_next",
        "rules": [
            {
                "t": "delete",
                "p": "data",
                "pt": "msg"
            },
            {
                "t": "set",
                "p": "trigger",
                "pt": "msg",
                "to": "true",
                "tot": "bool"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 722.833740234375,
        "y": 613.9404296875,
        "wires": [
            [
                "bffe3c19.05eca"
            ]
        ]
    },
    {
        "id": "bc94147b.93aae8",
        "type": "delay",
        "z": "8e729ba9.64339",
        "name": "",
        "pauseType": "delay",
        "timeout": "3",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "x": 450.119384765625,
        "y": 498.1904602050781,
        "wires": [
            [
                "865c84e8.d62208"
            ]
        ]
    },
    {
        "id": "2fee4419.3c3344",
        "type": "catch",
        "z": "8e729ba9.64339",
        "name": "",
        "scope": null,
        "x": 859.3216552734375,
        "y": 354.7142639160156,
        "wires": [
            [
                "aef9c512.2f577"
            ]
        ]
    },
    {
        "id": "351e3ad4.3ff3ee",
        "type": "function",
        "z": "8e729ba9.64339",
        "name": "payload_to_JSON",
        "func": "var data = msg.payload;\nconsole.log(\"payload data: length = \" + data.length);\ndata = data.trim();\nconsole.log(\"trimmed data: length = \" + data.length);\n\nmsg.payload = JSON.parse(data);\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 566.2501220703125,
        "y": 435.9642333984375,
        "wires": [
            [
                "10cdd636.bf60f2"
            ]
        ]
    },
    {
        "id": "733f4ba2.091bb4",
        "type": "delay",
        "z": "8e729ba9.64339",
        "name": "",
        "pauseType": "delay",
        "timeout": "5",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "x": 413.0121765136719,
        "y": 616.6191101074219,
        "wires": [
            [
                "865c84e8.d62208"
            ]
        ]
    },
    {
        "id": "d51fec69.4ff1b",
        "type": "debug",
        "z": "8e729ba9.64339",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "x": 1267.0593872070312,
        "y": 574.0531921386719,
        "wires": []
    },
    {
        "id": "65655784.e0c5c8",
        "type": "switch",
        "z": "8e729ba9.64339",
        "name": "queueCount > 0",
        "property": "queueCount",
        "propertyType": "msg",
        "rules": [
            {
                "t": "gt",
                "v": "0",
                "vt": "num"
            },
            {
                "t": "else"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 2,
        "x": 672.5595092773438,
        "y": 731.4818420410156,
        "wires": [
            [
                "733f4ba2.091bb4"
            ],
            []
        ]
    },
    {
        "id": "68535fdd.6918c8",
        "type": "inject",
        "z": "8e729ba9.64339",
        "name": "",
        "topic": "",
        "payload": "{\"group\":[{\"v\":1,\"d\":0.3},{\"v\":2,\"d\":0.3}]}",
        "payloadType": "str",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 221.25,
        "y": 462.5,
        "wires": [
            [
                "351e3ad4.3ff3ee",
                "bc94147b.93aae8"
            ]
        ]
    },
    {
        "id": "20fd15c1.ae86ca",
        "type": "change",
        "z": "8e729ba9.64339",
        "name": "queue_reset",
        "rules": [
            {
                "t": "set",
                "p": "reset",
                "pt": "msg",
                "to": "1",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "input_for",
                "pt": "msg",
                "to": "irrigation_queue",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 430,
        "y": 887.5,
        "wires": [
            [
                "bffe3c19.05eca"
            ]
        ]
    },
    {
        "id": "23f60ce8.2b488c",
        "type": "inject",
        "z": "8e729ba9.64339",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 201.25,
        "y": 887.5,
        "wires": [
            [
                "20fd15c1.ae86ca"
            ]
        ]
    }
]

**Comment by shady2k** [comment]
Sorry, but I can't import your example. Could you check it?

**Comment by githubbuh** [comment]
here is a copy that i have exported, re-imported, and confirmed that the sequence will demonstrate the defect with version 0.2.2

[{"id":"9c1b5f61.d975a8","type":"tab","label":"Queue_Defect","disabled":false,"info":""},{"id":"66b5b34c.28d8ec","type":"function","z":"9c1b5f61.d975a8","name":"group_str_parse","func":"var array = [];\nvar seqStr;\nvar cntStr;\nvar lastStr;\nvar runMode;\nvar runEvent;\n\n\nfor (var i=0; i<msg.payload.group.length;i++) {\n// add 1 to i to fix off-by-one so that the first\n// is 1\n    seqStr = i + 1;\n    cntStr = msg.payload.group.length;\n    lastStr = \"false\";\n    runMode = msg.run_mode;\n    runEvent = msg.run_event;\n\n    if ((msg.payload.group.length - i) == 1)\n    {\n        lastStr = \"true\";\n    }\n    \n    msg.payload.group[i].seq = seqStr;\n    msg.payload.group[i].cnt = cntStr;\n    msg.payload.group[i].last = lastStr;\n    msg.payload.group[i].run_event = runEvent;\n    \n    if (runMode == \"batch\")\n    {\n        msg.payload.group[i].run_mode = runMode;\n    }\n    else if (runMode == \"calendar\")\n    {\n        msg.payload.group[i].run_mode = runMode;\n    }\n    \n    array.push({payload: msg.payload.group[i]});\n}\n\nreturn [array];","outputs":1,"noerr":0,"x":785,"y":440,"wires":[["f7711b5d.d2ccf8"]]},{"id":"f998d438.45cd9","type":"debug","z":"9c1b5f61.d975a8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":1052.3931884765625,"y":383.8213653564453,"wires":[]},{"id":"f7711b5d.d2ccf8","type":"simple-queue","z":"9c1b5f61.d975a8","name":"irrigation_queue","firstMessageBypass":false,"bypassInterval":"0","x":1036.9407958984375,"y":572.8689575195312,"wires":[["da53b4eb.f52908","b2e49ac1.1fd39"]]},{"id":"d00054ac.32de78","type":"change","z":"9c1b5f61.d975a8","name":"queue_move_to_next","rules":[{"t":"delete","p":"data","pt":"msg"},{"t":"set","p":"trigger","pt":"msg","to":"1","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":722.833740234375,"y":613.9404296875,"wires":[["f7711b5d.d2ccf8"]]},{"id":"63df9fe.2dadc6","type":"delay","z":"9c1b5f61.d975a8","name":"","pauseType":"delay","timeout":"3","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":450.119384765625,"y":498.1904602050781,"wires":[["d00054ac.32de78"]]},{"id":"94b1aa6e.440638","type":"catch","z":"9c1b5f61.d975a8","name":"","scope":null,"x":859.3216552734375,"y":354.7142639160156,"wires":[["f998d438.45cd9"]]},{"id":"8b96de62.38be68","type":"function","z":"9c1b5f61.d975a8","name":"payload_to_JSON","func":"var data = msg.payload;\nconsole.log(\"payload data: length = \" + data.length);\ndata = data.trim();\nconsole.log(\"trimmed data: length = \" + data.length);\n\nmsg.payload = JSON.parse(data);\nreturn msg;","outputs":1,"noerr":0,"x":566.2501220703125,"y":435.9642333984375,"wires":[["66b5b34c.28d8ec"]]},{"id":"b2e49ac1.1fd39","type":"delay","z":"9c1b5f61.d975a8","name":"","pauseType":"delay","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":413.0121765136719,"y":616.6191101074219,"wires":[["d00054ac.32de78"]]},{"id":"da53b4eb.f52908","type":"debug","z":"9c1b5f61.d975a8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":1267.0593872070312,"y":574.0531921386719,"wires":[]},{"id":"8875bbe7.1cf568","type":"inject","z":"9c1b5f61.d975a8","name":"","topic":"","payload":"{\"group\":[{\"v\":1,\"d\":0.3},{\"v\":2,\"d\":0.3}]}","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":221.25,"y":462.5,"wires":[["8b96de62.38be68","63df9fe.2dadc6"]]},{"id":"29d8f6cf.5e82b2","type":"change","z":"9c1b5f61.d975a8","name":"queue_reset","rules":[{"t":"set","p":"reset","pt":"msg","to":"1","tot":"str"},{"t":"set","p":"input_for","pt":"msg","to":"irrigation_queue","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":430,"y":887.5,"wires":[["f7711b5d.d2ccf8"]]},{"id":"96b93a9d.4abbc","type":"inject","z":"9c1b5f61.d975a8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":201.25,"y":887.5,"wires":[["29d8f6cf.5e82b2"]]}]

**Comment by shady2k** [comment]
Ah, ok. I'm understand your problem. This happens because you don't delete "queueCount" from message before send it with "trigger" property. Simple queue node add "queueCount" property in each outgoing message. In your case, node receive message with two properties in same time, "trigger" and "queueCount", but "queueCount" property has more priority and this recursion leads to infinity loop.  You need to delete "queueCount" property before send it to simple queue node. In your "queue_move_to_next" node, you need to add delete msg.queueCount.
For prevent this situations in future, I'm rename "queueCount" property inside outgoing messages to "_queueCount", so no more infinity loops will occured. You don't need change anything, just download version 0.2.3.

Thanks for feedback!

Fixed in c244a9c44138e4d5de8d012fcaa5ed87383a0ad4

**Comment by githubbuh** [comment]
thank you for the quick response.  just to be sure, outbound messages with have _queueCount.  if an incoming message has msg.queueCount, the property will be ignored?

Oh, wait.  hehe.  i get it.  queueCount has to be there to query the queue depth.

**Comment by shady2k** [comment]
Yes, message with queueCount property returns number of messages left in the queue. This is from readme:
queueCount: If a message is received with this property, node will send message with number of messages left in the queue in _queueCount property. This message won't store in queue.
What should I update in readme?

**Comment by githubbuh** [comment]
What do you think of this?

**Inputs**

**trigger**: If a message is received with this property, one message from the queue will be released. The outbound message will have a _queueCount property with number of messages left in the queue.  _queueCount will not include the message triggered. For example, if the message triggered is the last one in the queue, _queueCount will be 0 (zero).  

**reset**: If a message is received with the reset property, all messages in the queue will be cleared.  In addition, the node will not forward the incoming reset message for processing by any subsequent nodes in the sequence.

**ttl**: If a message is received with this property, a message will be added to the queue and will live in the queue for specific value in milliseconds. The value of the ttl must be a non-negative integer (0 <= n), describing the ttl period in milliseconds. Thus a value of 1000 means that a message added to the queue will live in the queue for 1 second.  However, if another message is received by the node in less than 1 second, and the message has a trigger property, and the only message in the queue is the one with the ttl = 1000, the message will be released.  _(((((IS THIS TRUE OR NOT?)))  if not, then what do you mean when you say, “or until delivered”?_

**queueCount**: If a message is received with this property, node will send message with number of messages left in the queue in _queueCount property. This message won't store in queue.
Input Hierarchy

The following illustrates how the node will respond if more than one of the properties listed above is included in an incoming message.

#1 **reset** -- the highest priority.  if a message has a reset property, all other properties will be ignored.

#2 **queueCount** -- will override ttl and trigger.  The resulting outbound message will include the _queueCount property and the queueCount property will be removed.  Any other properties on the incoming message will be ignored.

#3 **trigger** -- higher priority than ttl.  Items released from the queue as a result of a trigger message will include a _queueCount property.  If the message has a ttl property, it will be ignored.

#4 **ttl** -- after the delay specified by the ttl property, the released message will include a _queueCount property.

**Comment by shady2k** [comment]
ttl has other meaning. Thanks for help! Please check readme now. Any suggestions?
896509095800821c8398a011f3e737b5af469d1f

**Comment by githubbuh** [comment]
Just upgraded to 0.2.5.  looks good. _queuetimestamp represents when the item was added to queue?

**Comment by shady2k** [comment]
Yes, _queuetimestamp is used to clear old messages with ttl property if they expired.
