### ISSUE TITLE
Queue firing will before trigger is received?

### ISSUE THREAD

**Issue by Swiftnesses** [shady2k/node-red-contrib-simple-message-queue#8]
Hello, 

I have the attached flow...

The issue is, if I sent one msg (let's call it msg1) and then send msg2, the flow is triggered - before the flow has completed msg1 and got to the trigger node. Any ideas why?

**Comment by Swiftnesses** [comment]
<img width="1047" alt="screenshot 2019-02-07 at 13 44 17" src="https://user-images.githubusercontent.com/1001877/52415369-b20fd880-2ade-11e9-8133-a1ec1cf4b82d.png">

**Comment by Swiftnesses** [comment]
Update, confirmed it queues correctly if I queue multiple msg1's, but if during that time I send a msg2, it breaks the queue and is actioned straight away...

**Comment by shady2k** [comment]
Can you export your flow and post here?

**Comment by Swiftnesses** [comment]
`[{"id":"a0a12d74.93df","type":"debug","z":"f8887b8f.b20468","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":728.1666717529297,"y":114.66667461395264,"wires":[]},{"id":"4ea76ef4.0160c","type":"inject","z":"f8887b8f.b20468","name":"alarm trigger","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":105.1666488647461,"y":149.8888897895813,"wires":[["6a2146c.b045eb8"]]},{"id":"786a05e1.341ebc","type":"function","z":"f8887b8f.b20468","name":"SimpleBlockingQueue","func":"context.queue = context.queue || [];\n\nvar totalAllowedQueueSize = 20;\nvar mqtt_connected = false;\nvar blocked = false;\n\n// mqtt out node\nvar nextNode = RED.nodes.getNode(\"ae7f8962.dd8b18\");\n// status check\nmqtt_connected = nextNode.brokerConn.connected;\nif (context.queue.length >= totalAllowedQueueSize) blocked = true;\n\nif (msg.payload.op == \"reset\"  ) {\n   context.queue = [];\n} else if ( msg.payload.op == \"trigger\" ) {\n    // dequeue\n    if ( context.queue.length === 0 ) msg = null; // no action\n    else {\n       if ( mqtt_connected ) msg.payload = context.queue.shift();\n    }\n} else {\n    // enqueue\n    if ( !blocked ) context.queue.push(msg.payload);\n}\n\nif (mqtt_connected) {\n    if( !blocked )\n        node.status({fill:\"green\",shape:\"ring\",text: '('+context.queue.length+') stored,connected' });\n    else \n        node.status({fill:\"red\",shape:\"ring\",text: 'blocked,('+context.queue.length+') stored,connected' });\n} else {\n    if( !blocked ) \n        node.status({fill:\"red\",shape:\"ring\",text: '('+context.queue.length+') stored,disconnected' });\n    else\n        node.status({fill:\"red\",shape:\"ring\",text: 'blocked,('+context.queue.length+') stored,disconnected' });\n}\n\nreturn msg;","outputs":1,"noerr":0,"x":528.1666717529297,"y":167.22222328186035,"wires":[["a0a12d74.93df","ae7f8962.dd8b18"]]},{"id":"614fc9a1.8f7bb8","type":"inject","z":"f8887b8f.b20468","name":"report trigger","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":105.16664123535156,"y":192.88888931274414,"wires":[["a73b7a92.6b5058"]]},{"id":"6a2146c.b045eb8","type":"function","z":"f8887b8f.b20468","name":"alarm generator","func":"\nvar trigger  = Math.floor(Math.random() * 6);\n\nmsg.payload.timestamp = Date.now();\nswitch ( trigger ) {\ncase 0 :\ncase 2 :\ncase 4 :\n    msg.payload.op = 'report';\n    msg.payload.priority = 1;\n    msg.payload.task = 'Gas Leak';\n    break;  \ncase 1 :\ncase 3 :\ncase 5 :\n    msg.payload.op = 'report';\n    msg.payload.priority = 2;\n    msg.payload.task = 'Water Leak';\n    break;    \ndefault:\n    msg.payload.op = 'report';\n    msg.payload.priority = 'low';\n    msg.payload.task = 'Gas Task';\n    break;\n}\n\nreturn msg;","outputs":1,"noerr":0,"x":294.1666717529297,"y":151.11111164093018,"wires":[["786a05e1.341ebc"]]},{"id":"a73b7a92.6b5058","type":"function","z":"f8887b8f.b20468","name":"mqtt out trigger","func":"msg.payload = { op : 'trigger' } ;\nreturn msg;","outputs":1,"noerr":0,"x":294.1666679382324,"y":194.1111125946045,"wires":[["786a05e1.341ebc"]]},{"id":"ae7f8962.dd8b18","type":"mqtt out","z":"f8887b8f.b20468","name":"MQTT pub - node1/alarm","topic":"node1/alarm","qos":"","retain":"","broker":"d139ad3f.b28af","x":762.1666717529297,"y":215.77779293060303,"wires":[]},{"id":"2e679e40.1f3272","type":"mosca in","z":"f8887b8f.b20468","mqtt_port":"1883","mqtt_ws_port":"","name":"","username":"","password":"","dburl":"","x":121.16667175292969,"y":284.8888912200928,"wires":[["248405cc.406f8a"]]},{"id":"248405cc.406f8a","type":"debug","z":"f8887b8f.b20468","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":314.1666717529297,"y":284.7777805328369,"wires":[]},{"id":"ff2a51fd.27ce6","type":"debug","z":"f8887b8f.b20468","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":342.1666679382324,"y":329.7777805328369,"wires":[]},{"id":"a1bd693d.21c098","type":"mqtt in","z":"f8887b8f.b20468","name":"MQTT sub - node1/alarm","topic":"node1/alarm","qos":"2","broker":"d139ad3f.b28af","x":131.1666717529297,"y":329.8888912200928,"wires":[["ff2a51fd.27ce6"]]},{"id":"bd1934b2.be82a8","type":"inject","z":"f8887b8f.b20468","name":"reset trigger","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":106.16667175292969,"y":233.88889122009277,"wires":[["c25a3456.5d7378"]]},{"id":"c25a3456.5d7378","type":"function","z":"f8887b8f.b20468","name":"reset trigger","func":"msg.payload = { op : 'reset' } ;\nreturn msg;\n","outputs":1,"noerr":0,"x":284.1666564941406,"y":234.31945991516113,"wires":[["786a05e1.341ebc"]]},{"id":"d139ad3f.b28af","type":"mqtt-broker","z":"","broker":"localhost","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","willTopic":"","willQos":"0","willPayload":""}]`

**Comment by shady2k** [comment]
This flow doesn't use my node.
Please check "Bypass first message?" in simple queue node properties, it's true by default, you need to uncheck it.

**Comment by Swiftnesses** [comment]
Argh, wrong clipboard!

`[{"id":"a0a12d74.93df","type":"debug","z":"f8887b8f.b20468","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":728.1666717529297,"y":114.66667461395264,"wires":[]},{"id":"4ea76ef4.0160c","type":"inject","z":"f8887b8f.b20468","name":"alarm trigger","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":105.1666488647461,"y":149.8888897895813,"wires":[["6a2146c.b045eb8"]]},{"id":"786a05e1.341ebc","type":"function","z":"f8887b8f.b20468","name":"SimpleBlockingQueue","func":"context.queue = context.queue || [];\n\nvar totalAllowedQueueSize = 20;\nvar mqtt_connected = false;\nvar blocked = false;\n\n// mqtt out node\nvar nextNode = RED.nodes.getNode(\"ae7f8962.dd8b18\");\n// status check\nmqtt_connected = nextNode.brokerConn.connected;\nif (context.queue.length >= totalAllowedQueueSize) blocked = true;\n\nif (msg.payload.op == \"reset\"  ) {\n   context.queue = [];\n} else if ( msg.payload.op == \"trigger\" ) {\n    // dequeue\n    if ( context.queue.length === 0 ) msg = null; // no action\n    else {\n       if ( mqtt_connected ) msg.payload = context.queue.shift();\n    }\n} else {\n    // enqueue\n    if ( !blocked ) context.queue.push(msg.payload);\n}\n\nif (mqtt_connected) {\n    if( !blocked )\n        node.status({fill:\"green\",shape:\"ring\",text: '('+context.queue.length+') stored,connected' });\n    else \n        node.status({fill:\"red\",shape:\"ring\",text: 'blocked,('+context.queue.length+') stored,connected' });\n} else {\n    if( !blocked ) \n        node.status({fill:\"red\",shape:\"ring\",text: '('+context.queue.length+') stored,disconnected' });\n    else\n        node.status({fill:\"red\",shape:\"ring\",text: 'blocked,('+context.queue.length+') stored,disconnected' });\n}\n\nreturn msg;","outputs":1,"noerr":0,"x":528.1666717529297,"y":167.22222328186035,"wires":[["a0a12d74.93df","ae7f8962.dd8b18"]]},{"id":"614fc9a1.8f7bb8","type":"inject","z":"f8887b8f.b20468","name":"report trigger","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":105.16664123535156,"y":192.88888931274414,"wires":[["a73b7a92.6b5058"]]},{"id":"6a2146c.b045eb8","type":"function","z":"f8887b8f.b20468","name":"alarm generator","func":"\nvar trigger  = Math.floor(Math.random() * 6);\n\nmsg.payload.timestamp = Date.now();\nswitch ( trigger ) {\ncase 0 :\ncase 2 :\ncase 4 :\n    msg.payload.op = 'report';\n    msg.payload.priority = 1;\n    msg.payload.task = 'Gas Leak';\n    break;  \ncase 1 :\ncase 3 :\ncase 5 :\n    msg.payload.op = 'report';\n    msg.payload.priority = 2;\n    msg.payload.task = 'Water Leak';\n    break;    \ndefault:\n    msg.payload.op = 'report';\n    msg.payload.priority = 'low';\n    msg.payload.task = 'Gas Task';\n    break;\n}\n\nreturn msg;","outputs":1,"noerr":0,"x":294.1666717529297,"y":151.11111164093018,"wires":[["786a05e1.341ebc"]]},{"id":"a73b7a92.6b5058","type":"function","z":"f8887b8f.b20468","name":"mqtt out trigger","func":"msg.payload = { op : 'trigger' } ;\nreturn msg;","outputs":1,"noerr":0,"x":294.1666679382324,"y":194.1111125946045,"wires":[["786a05e1.341ebc"]]},{"id":"ae7f8962.dd8b18","type":"mqtt out","z":"f8887b8f.b20468","name":"MQTT pub - node1/alarm","topic":"node1/alarm","qos":"","retain":"","broker":"d139ad3f.b28af","x":762.1666717529297,"y":215.77779293060303,"wires":[]},{"id":"2e679e40.1f3272","type":"mosca in","z":"f8887b8f.b20468","mqtt_port":"1883","mqtt_ws_port":"","name":"","username":"","password":"","dburl":"","x":121.16667175292969,"y":284.8888912200928,"wires":[["248405cc.406f8a"]]},{"id":"248405cc.406f8a","type":"debug","z":"f8887b8f.b20468","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":314.1666717529297,"y":284.7777805328369,"wires":[]},{"id":"ff2a51fd.27ce6","type":"debug","z":"f8887b8f.b20468","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":342.1666679382324,"y":329.7777805328369,"wires":[]},{"id":"a1bd693d.21c098","type":"mqtt in","z":"f8887b8f.b20468","name":"MQTT sub - node1/alarm","topic":"node1/alarm","qos":"2","broker":"d139ad3f.b28af","x":131.1666717529297,"y":329.8888912200928,"wires":[["ff2a51fd.27ce6"]]},{"id":"bd1934b2.be82a8","type":"inject","z":"f8887b8f.b20468","name":"reset trigger","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":106.16667175292969,"y":233.88889122009277,"wires":[["c25a3456.5d7378"]]},{"id":"c25a3456.5d7378","type":"function","z":"f8887b8f.b20468","name":"reset trigger","func":"msg.payload = { op : 'reset' } ;\nreturn msg;\n","outputs":1,"noerr":0,"x":284.1666564941406,"y":234.31945991516113,"wires":[["786a05e1.341ebc"]]},{"id":"d139ad3f.b28af","type":"mqtt-broker","z":"","broker":"localhost","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","willTopic":"","willQos":"0","willPayload":""}]`

**Comment by Swiftnesses** [comment]
It works if the TTS input is the same, i.e. msg1, but if another TTS input is received, it breaks through the queue and things get weird...

**Comment by shady2k** [comment]
Ok, but I'm still waiting for the test flow, in your comment flow without my node.

**Comment by Swiftnesses** [comment]
Sorry, I'm new to Node Red, here it is:

`[{"id":"f7b19187.74cb7","type":"api-call-service","z":"a8352ab2.7ac8b8","name":"Announce","server":"9a109606.fffb28","service_domain":"tts","service":"google_say","data":"{\"entity_id\":\"media_player.living_room_2\",\"message\":\"{{sonos_tts}}\"}","render_data":true,"mergecontext":"","output_location":"","output_location_type":"none","x":440,"y":910,"wires":[["5d0bea2.741de14"]]},{"id":"c95f1027.5bb1d","type":"api-call-service","z":"a8352ab2.7ac8b8","name":"Sonos Snapshot","server":"9a109606.fffb28","service_domain":"media_player","service":"sonos_snapshot","data":"","render_data":false,"mergecontext":"","output_location":"","output_location_type":"none","x":240,"y":910,"wires":[["f7b19187.74cb7","f4a4a145.51e1b"]]},{"id":"9c337346.1fa7d","type":"api-call-service","z":"a8352ab2.7ac8b8","name":"Sonos Restore","server":"9a109606.fffb28","service_domain":"media_player","service":"sonos_restore","data":"{\"entity_id\":\"media_player.living_room_2\"}","render_data":false,"mergecontext":"","output_location":"payload","output_location_type":"msg","x":780,"y":910,"wires":[["7caa682.5156198"]]},{"id":"5d0bea2.741de14","type":"delay","z":"a8352ab2.7ac8b8","name":"","pauseType":"delay","timeout":"10","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":600,"y":910,"wires":[["9c337346.1fa7d"]]},{"id":"e0fc930.ca80a7","type":"comment","z":"a8352ab2.7ac8b8","name":"How to use","info":"Send the subflow:\n\nmsg: sonos_tts\n\ntype: string","x":530,"y":670,"wires":[]},{"id":"9b7756fb.174358","type":"simple-queue","z":"a8352ab2.7ac8b8","name":"Queue","firstMessageBypass":true,"bypassInterval":"0","x":670,"y":720,"wires":[["c95f1027.5bb1d"]]},{"id":"7caa682.5156198","type":"change","z":"a8352ab2.7ac8b8","name":"","rules":[{"t":"move","p":"payload","pt":"msg","to":"trigger","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":990,"y":910,"wires":[["fe8bc4d4.4c7308","9b7756fb.174358","da80506.25c23b"]]},{"id":"fe8bc4d4.4c7308","type":"debug","z":"a8352ab2.7ac8b8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":1170,"y":910,"wires":[]},{"id":"f4a4a145.51e1b","type":"api-call-service","z":"a8352ab2.7ac8b8","name":"Update Variable","server":"9a109606.fffb28","service_domain":"variable","service":"set_variable","data":"{\"variable\":\"sonos_speaking\",\"value\":true}","render_data":true,"mergecontext":"","output_location":"","output_location_type":"none","x":460,"y":960,"wires":[[]]},{"id":"da80506.25c23b","type":"api-call-service","z":"a8352ab2.7ac8b8","name":"Update Variable","server":"9a109606.fffb28","service_domain":"variable","service":"set_variable","data":"{\"variable\":\"sonos_speaking\",\"value\":false}","render_data":true,"mergecontext":"","output_location":"","output_location_type":"none","x":1200,"y":960,"wires":[[]]},{"id":"9a109606.fffb28","type":"server","z":"","name":"Home Assistant"}]`

**Comment by shady2k** [comment]
Uncheck "Bypass first message?" checkbox.

![image](https://user-images.githubusercontent.com/3366415/52417384-d2e72680-2afc-11e9-98b2-7518670fbc22.png)

**Comment by Swiftnesses** [comment]
If I do that, how do I trigger the first message? Further, why would it work with 1 message type (perfectly), but only fail when another comes in?

**Comment by shady2k** [comment]
Sorry, but I'm don't understand. What do you mean about msg1 and msg2. What's difference between them?

**Comment by Swiftnesses** [comment]
The content of msg.sonos_tts

**Comment by Swiftnesses** [comment]
`
<img width="307" alt="screenshot 2019-02-07 at 14 33 57" src="https://user-images.githubusercontent.com/1001877/52418195-6d3b7000-2ae5-11e9-9f72-5960e39424b0.png">
`

**Comment by Swiftnesses** [comment]
After some tests, it works fine directly in a flow, but not in a subflow, I wonder why?

**Comment by shady2k** [comment]
Please update to latest 0.2.3 version.

**Comment by Swiftnesses** [comment]
I think I'm already using 0.2.3 (downloaded it a few hours ago?).

**Comment by githubbuh** [comment]
May i chime in.  swiftness.  i see that you are moving payload to trigger then sending the message to the queue.  because your message has a trigger property it will immediately release the item from the queue.  when a message arrives with a trigger property, doesn't matter the value of trigger, the queue will release the next item in the queue.  it is not necessary to have a trigger property to add an item to the queue.  just send a message with a payload.

seems like adding items to the queue and triggering their release should be discrete, different events.

is it possible for you to send a message that just has what you want to go into the queue.  then, when your sequence is ready to process the next item in the queue, send a message to the queue with just trigger=true so that an item will be released?

make sense?
