### ISSUE TITLE
Misunderstanding TTL?

### ISSUE THREAD

**Issue by Swiftnesses** [shady2k/node-red-contrib-simple-message-queue#9]
Hello,

Great module btw, thanks... :)

I have a scenario whereby I need messages to live in the queue for x seconds are they're added (not released x seconds apart, but x seconds from when they were added!). I assumed TTL would do this, but I cannot seem to get it to work?

Any help would be greatly appreciated.

Thanks.

**Comment by shady2k** [comment]
Yes, ttl will do what you want. You need to set msg.ttl property for incoming message in milliseconds (e.g. 5000 means 5 seconds). If message does not release in specificed time, it will be totally removed from queue after trigger event.
Here is a demo flow. First message will be bypassed (if you don't need such behavior uncheck"Bypass first message?" in queue node properties), next will be cleared from queue if you don't trigger it in 5 seconds.

```
[{"id":"49d5a0da.f779d","type":"simple-queue","z":"594d0ad8.637664","name":"queue1","firstMessageBypass":true,"bypassInterval":"0","x":520,"y":300,"wires":[["df316393.57c4"]]},{"id":"1036668e.04ee29","type":"inject","z":"594d0ad8.637664","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":300,"wires":[["309d6ade.501156"]]},{"id":"309d6ade.501156","type":"change","z":"594d0ad8.637664","name":"","rules":[{"t":"set","p":"ttl","pt":"msg","to":"5000","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":330,"y":300,"wires":[["49d5a0da.f779d"]]},{"id":"df316393.57c4","type":"debug","z":"594d0ad8.637664","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":760,"y":300,"wires":[]}]
```
